# FROM node:14.14.0-alpine
# WORKDIR /app
# COPY ./package.json ./
# RUN npm i
# COPY . .
# CMD [ "npm", "run", "start" ]

# Use the official Node.js image with Alpine Linux.
FROM node:14.14.0-alpine

# Set the working directory.
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory.
COPY package*.json ./

# Install the dependencies.
RUN npm install

# Copy the rest of the application code to the working directory.
COPY . .

# Expose the port the app runs on.
EXPOSE 3000

# Command to run the application.
CMD ["npm", "run", "start"]
