# Use the official Node.js image.
FROM node:14.14.0-alpine

# Create and change to the app directory.
WORKDIR /app

# Copy application dependency manifests to the container image.
COPY package*.json ./

# Install dependencies.
RUN npm install --legacy-peer-deps

# Copy the local code to the container image.
COPY . .

# Set the command to start the server.
CMD ["npm", "start"]