version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ${PGUSER}   # Ensure this is set in your .env file
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE} # Ensure this is set in your .env file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}
    depends_on:
      - postgres
      - redis

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}
    depends_on:
      - api

volumes:
  postgres_data:
