# FROM node:14.14.0-alpine
# WORKDIR /app
# COPY ./package.json ./
# RUN npm i
# COPY . .
# EXPOSE 5000
# CMD ["npm", "run", "dev" ]

FROM node:14.14.0-alpine

# Create and set the working directory.
WORKDIR /app

# Copy package.json and package-lock.json files.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application code.
COPY . .

# Expose the application port.
EXPOSE 5000

# Command to run the application.
CMD ["npm", "run", "dev"]